### ISSUE TITLE
Enforce declarations order with stylelint

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/stylelint-config-wagtail#14]
Initially mentioned in https://github.com/wagtail/wagtail/issues/5246#issuecomment-485861248, and discussed again in a UI team meeting.

We want to use [stylelint-order](https://github.com/hudochenkov/stylelint-order) for this, we want to enforce mixins are first in declarations, and I think that’s about it.

**Comment by PaarthAgarwal** [comment]
May I go ahead with this issue?

**Comment by lb-** [comment]
Sure. As per the comments above - goal is just to enforce mixins first.
