### ISSUE TITLE
Add a linting rule to block additional usage of `text-transform`

### ISSUE THREAD

**Issue by lb-** [wagtail/stylelint-config-wagtail#15]
Adding text-transform: uppercase (or others) creates added friction for translated content.

While it may not be critical we want to ensure that our stylelint config makes it simple to make things translatable and usable.

_Originally posted by @lb- in https://github.com/wagtail/wagtail/issues/7624#issuecomment-1058879006_

**Comment by PaarthAgarwal** [comment]
I'd like to work on this issue. Please assign it to me.
Thank you!

**Comment by lb-** [comment]
@PaarthAgarwal we don't really use the assign too much, just give it a start and the raise a PR that references this issue when you are ready

**Comment by PaarthAgarwal** [comment]
Hi @lb- I have opened PR #16 to solve this issue.  If need be suggest any changes.
