### ISSUE TITLE
Add ability to enforce BEM classes with prefix

### ISSUE THREAD

**Issue by lb-** [wagtail/stylelint-config-wagtail#19]
## Problem

* Wagtail's code is meant to use BEM classes, however this has never been enforced and only really partially adopted.
* Enforcing this at the stylelint level will help the project align with this standard

## Details

* It is unclear if this should be in the base stylelint config or as a separate plugin also exported by this package.
* It will be important to be able to set a prefix (e.g. `w-header w-header--merged` OR `wx-header wx-header--merged` ).

## Links

* https://github.com/simonsmith/stylelint-selector-bem-pattern which uses https://github.com/postcss/postcss-bem-linter
* http://getbem.com/naming/
* https://github.com/wagtail/wagtail/discussions/7689

**Comment by thibaudcolas** [comment]
Discussed in UI team:

- Torchbox has this set up [with `selector-class-pattern`](https://github.com/torchbox/stylelint-config-torchbox/blob/2d1dffc2d6af49d1327e66daf51d520dd50c5fdc/config.js#L22-L31).
- We need to try this without a plugin and see what happens
- Then try a plugin if needed

**Comment by lb-** [comment]
We would probably have to ignore some folders - e.g. overrides and draftail as we may not have control over these classes for external libraries and Django.
