### ISSUE TITLE
Add ability to block union classes (via parent selector)

### ISSUE THREAD

**Issue by lb-** [wagtail/stylelint-config-wagtail#20]
# Problem

The ITCSS guide recommends that nesting be limited and that full selectors provides a more ergonomic way to scan through and search code.

https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/

> Limit nesting to 2 levels. Many developers think that using the [parent selector](https://sass-lang.com/documentation/style-rules/parent-selector) (&) is a requirement just because they use Sass. There’s nothing wrong with flat structure with full selectors expanded, either. Often it’s easier to scan and search the code.
```
.c-teaser {
   padding: 2em;
}

.c-teaser--small {
  padding: 1em;
}

.c-teaser__title {
  font-size: 2em;
}
```
> Use the style you prefer, but avoid deep nesting, which results in overqualified selectors. Those are against the spirit of ITCSS.

# Details

* With the Stylelint SCSS library we can enforce no union class, this makes it easier for us to adopt less nesting in the future and makes it easier to read through and search for classes as they are in the styles.
* https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/selector-no-union-class-name/README.md
* ❌ `.w-header { &__subtitle { background-color: green; } }`
* 👍  `.w-header { .w-header__subtitle { background-color: green; } }`

**Comment by thibaudcolas** [comment]
Discussed in today’s UI team meeting – UI team poll on whether we want to disallow usage of union class names (have to consider what we have in guidelines, and what can be enforced)

**Comment by lb-** [comment]
Poll created - https://wagtailcms.slack.com/archives/C0P6APKH9/p1655522574042589

## Feedback needed - block or allow scss union classes. 

We had a discussion at the UI team a few weeks ago about using scss's & when building classes (specifically BEM classes). One thing that came up is we have little consistency in this area and that when building classes with the unions approach it becomes harder to search through the code for a class. 

Proposal is that we block union classes so that a linting error will be raised if you do this (example below).

:x: `.w-header { &--merged { background-color: green; } }`
✅ `.w-header { .w-header--merged { background-color: green; } }`

It does not appear to be possible to enforce the other way (union classes MUST be used) so we either add more strictness or leave as is. 

Emoji Poll:
 :building_construction: - add more strictness and enforce full classes only 
 :shrug: - leave as is - anyone can do what they think makes sense 

The downside of enforcing this is that it can be more verbose, the upside is that the edge cases where using & incorrectly won't bite new devs and searching through code / find/replace become easier. Plus new devs will not have to 'decide' what to do, there will be a clear right way to do this.

**Comment by Scotchester** [comment]
Just to clarify -- the CSS output of these two lines is not identical, correct?

> ❌ `.w-header { &--merged { background-color: green; } }`
> ✅ `.w-header { .w-header--merged { background-color: green; } }`

The first would result in

```css
.w-header--merged { background-color: green; }
```

but the second would result in

```css
.w-header .w-header--merged { background-color: green; }
```

If we want to avoid union classes (which is my vote 🏗️ – except for creating pseudoclasses or pseudoelements), then we want to look like the first example in your original post, which is just not nested.

I'm not sure if that nuance is enforceable with Stylelint, though.

**Comment by lb-** [comment]
Thanks Scott. 
The scss rule will only block classes being generated with the `&`. 

Using it for nesting/ pseudo classes / etc won't be blocked.

**Comment by lb-** [comment]
Updates

- The snippet above is incorrect, will fix it up. Probably a good example of how the use of building up classes with `&` can cause confusion. 
- General consensus is that this is a good idea, makes the code easier to read for humans and machines.
